import { IGame } from "../Interfaces"

const ripple: IGame = {
  "name": "Ripple",
  "author": "Yihao",
  "time": new Date("2020-08-31T12:00:00.000Z"),
  "description": "This game resembles the ripple on the surface of water. This game is an example of using only the size property to style the cells.",
  "refreshFrequency": 10,
  "width": 19,
  "height": 19,
  "seeds": [
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ]
  ],
  "surviveRangeLower": 2,
  "surviveRangeUpper": 7,
  "reproductionRangeLower": 1,
  "reproductionRangeUpper": 6,
  "borderPolicy": "roll",
  "styles": [
    [
      {
        "size": 20,
        "color": "#87c6db",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 50,
        "color": "#45b4d9",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 50,
        "color": "#45b4d9",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 20,
        "color": "#87c6db",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 20,
        "color": "#87c6db",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 20,
        "color": "#87c6db",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 20,
        "color": "#87c6db",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 20,
        "color": "#87c6db",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 20,
        "color": "#87c6db",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      }
    ],
    [
      {
        "size": 70,
        "color": "#037da4",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 70,
        "color": "#037da4",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 70,
        "color": "#037da4",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 70,
        "color": "#037da4",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 70,
        "color": "#037da4",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 70,
        "color": "#037da4",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 70,
        "color": "#037da4",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 90,
        "color": "#0282ac",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 90,
        "color": "#0282ac",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      }
    ]
  ]
};

export default ripple;