import { IGame } from "../Interfaces";

const defaultTemplate: IGame = {
  "name": "Default",
  "author": "Yihao",
  "time": new Date("2020-08-31T12:00:00.000Z"),
  "description": "This is the default template.",
  "refreshFrequency": 5,
  "width": 15,
  "height": 15,
  "seeds": [
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      true,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      true,
      false,
      false,
      false
    ],
    [
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      true,
      true,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      false
    ],
    [
      false,
      true,
      true,
      true,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      true,
      true,
      false
    ],
    [
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      true,
      true,
      false
    ],
    [
      false,
      false,
      false,
      true,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      true,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ]
  ],
  "surviveRangeLower": 2,
  "surviveRangeUpper": 3,
  "reproductionRangeLower": 3,
  "reproductionRangeUpper": 3,
  "borderPolicy": "dead",
  "styles": [
    [
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      },
      {
        "size": 80,
        "color": "#eee",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 0
      }
    ],
    [
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      },
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      },
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      },
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      },
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      },
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      },
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      },
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      },
      {
        "size": 80,
        "color": "green",
        "backgroundColor": "white",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 3
      }
    ]
  ]
};

export default defaultTemplate;