import { IGame } from "../Interfaces";

const go: IGame = {
  "name": "Go",
  "author": "Yihao",
  "time": new Date("2020-08-14T06:24:55.954Z"),
  "description": "This game resembles the board of a Go game.",
  "refreshFrequency": 5,
  "width": 19,
  "height": 19,
  "seeds": [
    [
      false,
      true,
      false,
      true,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      true,
      false
    ],
    [
      false,
      true,
      false,
      true,
      true,
      false,
      true,
      true,
      true,
      false,
      true,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      true
    ],
    [
      false,
      true,
      false,
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false
    ],
    [
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      true,
      true,
      false,
      true
    ],
    [
      false,
      false,
      true,
      true,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      false,
      false,
      true
    ],
    [
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      true,
      true,
      true,
      false,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      false
    ],
    [
      true,
      true,
      true,
      false,
      true,
      false,
      false,
      false,
      false,
      true,
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      false,
      true
    ],
    [
      false,
      true,
      true,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      true,
      true
    ],
    [
      true,
      false,
      false,
      true,
      true,
      true,
      true,
      false,
      true,
      true,
      true,
      true,
      true,
      false,
      true,
      true,
      true,
      false,
      true
    ],
    [
      true,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      false,
      true,
      false,
      false,
      true
    ],
    [
      false,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      true,
      true
    ],
    [
      false,
      false,
      true,
      true,
      true,
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      true,
      false,
      true
    ],
    [
      true,
      false,
      true,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true
    ],
    [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      false,
      false,
      false,
      false,
      true,
      false,
      true
    ],
    [
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      false,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      true
    ],
    [
      true,
      true,
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      false,
      false
    ],
    [
      true,
      false,
      false,
      true,
      false,
      true,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      true
    ],
    [
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      false,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      true
    ],
    [
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      false,
      true,
      false,
      true,
      true,
      true,
      false,
      true,
      false,
      false
    ]
  ],
  "surviveRangeLower": 2,
  "surviveRangeUpper": 3,
  "reproductionRangeLower": 3,
  "reproductionRangeUpper": 3,
  "borderPolicy": "dead",
  "styles": [
    [
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#ffffff",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      }
    ],
    [
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      },
      {
        "size": 80,
        "color": "#020202",
        "backgroundColor": "#f8a027",
        "borderColor": "gray",
        "borderRadius": 50,
        "borderWidth": 0,
        "elevation": 4
      }
    ]
  ]
};

export default go;